# -*- coding: utf-8 -*-
"""FRONT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LuU0zfTv2bcQ4-OEyAtMHcrwOMqBuCLo
"""

pip install flask

from flask import Flask, render_template, request

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def form():
    if request.method == 'POST':
        name = request.form['name']
        last_name = request.form['last_name']
        date_of_birth = request.form['date_of_birth']
        gender = request.form['gender']
        blood_type = request.form['blood_type']
        diseases = request.form['diseases'].split(',')
        vaccine_type = request.form['vaccine_type']

        previous_vaccines = [
            {"name": "Tuberculosis", "date_time": "2001-01-10 10:00"},
            {"name": "Hepatitis B", "date_time": "2002-06-20 16:20"},
            {"name": "Varicela", "date_time": "2013-06-20 17:45"},
            {"name": "Influenza", "date_time": "2020-06-20 15:30"}
        ]

        return render_template('result.html', name=name, last_name=last_name, date_of_birth=date_of_birth,
                               gender=gender, blood_type=blood_type, diseases=diseases,
                               vaccine_type=vaccine_type, previous_vaccines=previous_vaccines)
    return render_template('form.html')

if __name__ == '__main__':
    app.run(debug=True)

form_html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario de Vacunación</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .form-container {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }
        .form-container h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        .form-container input, .form-container textarea {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        .form-container button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            font-size: 16px;
            cursor: pointer;
        }
        .form-container button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h2>Formulario de Vacunación</h2>
        <form method="POST" action="/submit">
            <input type="text" name="name" placeholder="Nombre" required>
            <input type="text" name="last_name" placeholder="Apellidos" required>
            <input type="date" name="date_of_birth" placeholder="Fecha de nacimiento (YYYY-MM-DD)" required>
            <input type="text" name="gender" placeholder="Género" required>
            <input type="text" name="blood_type" placeholder="Tipo de sangre" required>
            <textarea name="diseases" placeholder="Enfermedades (separadas por comas)" required></textarea>
            <input type="text" name="vaccine_type" placeholder="Tipo de vacuna a aplicar" required>
            <button type="submit">Enviar</button>
        </form>
    </div>
</body>
</html>
"""

with open("form.html", "w") as file:
    file.write(form_html)

from IPython.core.display import display, HTML

name = "Juan"
last_name = "Pérez"
date_of_birth = "1990-01-01"
gender = "Masculino"
blood_type = "O+"
diseases = ["Diabetes", "Hipertensión"]
vaccine_type = "COVID-19"

previous_vaccines = [
    {"name": "Tuberculosis", "date_time": "2001-01-10 10:00"},
    {"name": "Hepatitis B", "date_time": "2002-06-20 16:20"},
    {"name": "Varicela", "date_time": "2013-06-20 17:45"},
    {"name": "Influenza", "date_time": "2020-06-20 15:30"}
]


result_html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultado del Formulario</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }}
        .result-container {{
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 400px;
        }}
        .result-container h2 {{
            text-align: center;
            margin-bottom: 20px;
        }}
        .result-container p {{
            margin: 5px 0;
        }}
        .vaccine-list {{
            list-style-type: none;
            padding: 0;
        }}
        .vaccine-list li {{
            background-color: #f9f9f9;
            margin: 5px 0;
            padding: 10px;
            border-radius: 5px;
        }}
    </style>
</head>
<body>
    <div class="result-container">
        <h2>Datos Ingresados</h2>
        <p><strong>Nombre:</strong> {name}</p>
        <p><strong>Apellidos:</strong> {last_name}</p>
        <p><strong>Fecha de nacimiento:</strong> {date_of_birth}</p>
        <p><strong>Género:</strong> {gender}</p>
        <p><strong>Tipo de sangre:</strong> {blood_type}</p>
        <p><strong>Enfermedades:</strong> {', '.join(diseases)}</p>
        <p><strong>Tipo de vacuna a aplicar:</strong> {vaccine_type}</p>

        <h2>Vacunas previas</h2>
        <ul class="vaccine-list">
            {''.join([f"<li><strong>Nombre:</strong> {vaccine['name']}<br><strong>Fecha y hora:</strong> {vaccine['date_time']}</li>" for vaccine in previous_vaccines])}
        </ul>
    </div>
</body>
</html>
"""

display(HTML(result_html))